"""empty message

Revision ID: 130e13242c4
Revises: 1dcffe6bda2
Create Date: 2015-08-20 13:07:21.528915

"""

# revision identifiers, used by Alembic.
revision = '130e13242c4'
down_revision = '1dcffe6bda2'

from alembic import op
import sqlalchemy as sa
import  sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.Unicode(length=40), nullable=False))
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###

    conn = op.get_bind()
    sync_trigger(conn, 'documents', 'search_vector', ['name', 'content'])

def downgrade():

    conn = op.get_bind()
    sync_trigger(conn, 'documents', 'search_vector', ['name', 'content'])

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'content_hash')
    ### end Alembic commands ###
