"""empty message

Revision ID: 1dcffe6bda2
Revises: None
Create Date: 2015-08-19 13:22:40.416834

"""

# revision identifiers, used by Alembic.
revision = '1dcffe6bda2'
down_revision = None

from alembic import op
import sqlalchemy as sa
import  sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_search_vector', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    ### end Alembic commands ###

    conn = op.get_bind()
    sync_trigger(conn, 'documents', 'search_vector', ['name', 'content'])


def downgrade():
    conn = op.get_bind()
    sync_trigger(conn, 'documents', 'search_vector', ['name', 'content'])
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_search_vector', table_name='documents')
    op.drop_table('documents')
    ### end Alembic commands ###
