"""empty message

Revision ID: 23b56290135
Revises: 5283d3dace
Create Date: 2015-08-31 13:34:21.456363

"""

# revision identifiers, used by Alembic.
revision = '23b56290135'
down_revision = '5283d3dace'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chash', sa.Unicode(length=40), nullable=False))
    op.add_column('documents', sa.Column('mime', sa.Unicode(length=32), nullable=False))
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('path', sa.Unicode(length=255), nullable=False))
    op.add_column('documents', sa.Column('utility', sa.Unicode(length=32), nullable=False))
    op.create_index('idx_documents_chash', 'documents', ['chash'], unique=True)
    op.drop_index('idx_documents_name_url', table_name='documents')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_index('idx_documents_name_url', 'documents', ['name', 'url'], unique=True)
    op.drop_index('idx_documents_chash', table_name='documents')
    op.drop_column('documents', 'utility')
    op.drop_column('documents', 'path')
    op.drop_column('documents', 'pages')
    op.drop_column('documents', 'mime')
    op.drop_column('documents', 'chash')
    ### end Alembic commands ###
