"""empty message

Revision ID: 4f87da8586
Revises: 130e13242c4
Create Date: 2015-08-20 13:45:58.529332

"""

# revision identifiers, used by Alembic.
revision = '4f87da8586'
down_revision = '130e13242c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_documents_name_url', 'documents', ['name', 'url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_name_url', table_name='documents')
    ### end Alembic commands ###
