"""empty message

Revision ID: 5283d3dace
Revises: 11939eba9b7
Create Date: 2015-08-23 00:24:10.335390

"""

# revision identifiers, used by Alembic.
revision = '5283d3dace'
down_revision = '11939eba9b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_search_vector', table_name='documents')
    op.drop_column('documents', 'search_vector')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_documents_search_vector', 'documents', ['search_vector'], unique=False)
    ### end Alembic commands ###
