"""empty message

Revision ID: 75c9ebcc3f
Revises: None
Create Date: 2015-09-01 20:48:08.254082

"""

# revision identifiers, used by Alembic.
revision = '75c9ebcc3f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('path', sa.Unicode(length=255), nullable=False),
    sa.Column('mime', sa.Unicode(length=128), nullable=False),
    sa.Column('utility', sa.Unicode(length=32), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('chash', sa.Unicode(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_chash', 'documents', ['chash'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_chash', table_name='documents')
    op.drop_table('documents')
    ### end Alembic commands ###
